### ISSUE TITLE
newlines are ignored in Linux

### ISSUE THREAD

**Issue by wenzhenl** [mgmeyers/LineReader#2]
I read your code and run the demo with the test.txt attached in your repo. The result I got is 
1: 12345678910, but the expected results should be:
1: 1
2: 2
3: 3
....
right? It seems the newlines are ignored. I don't know whether it is system dependent thing, I am using Linux.

**Comment by mgmeyers** [comment]
Thanks for letting me know! It shouldn't be a problem that you're in Linux (I am too). What browser are you using?

**Comment by wenzhenl** [comment]
I am using latest version Firefox
