### ISSUE TITLE
Problem with CSV files with UTF-8

### ISSUE THREAD

**Issue by fernandohu** [mgmeyers/LineReader#5]
Hello, your library is very good, but there are some problems related to character encoding and chunk size.

For example: when trying to read the string "Alimentação", it reads "Alimentaç��o".

I investigated and this problem is caused by the slice method (from FileReader).

The problem happens when the file is chunked exactly over an UTF-8 character that has more than one byte. UTF-8 characters are stored with 1 up to 4 bytes. The problem will not appear if every UTF-8 character of a text file has 1 byte (for example, English language).

But when you try to use other languages, like Latin languages or Asian languages like Japanese or Chinese, you will notice that slice() method may chunk in the middle of a UTF-8 character.

Later, when the strings are glued, they end up forming one or more invalid characters. One or more questions marks appears like in the example I gave above.

I don't think there is a solution for this, because slice() method works at byte level.

**Comment by lvil** [comment]
Just went to issues being sure to see this one

**Comment by ikenfin** [comment]
@fernandohu seems that i resolved the problem. 
The idea is - check end of readed line on broken unicode character (**\uFFFD**), and if that exists - read again from previous position to chunkSize + one byte in recursion.
Unfortunately, this works slower, but only for non ASCII symbols.

Please look at my reader here for reference - https://github.com/ikenfin/fo-csv/blob/a098d60fda61fa912c3967021d6b6b5f69e20f46/frontend/foc_csv/src/helpers.js#L34
